package handlers

import (
	"net/http"
	_ "wifilogin/cmd/wifilogin/docs" // docs is generated by Swag CLI, you have to import it.
	"wifilogin/cmd/wifilogin/models"
	"wifilogin/version"

	"github.com/gin-gonic/gin"
	// swagger embed files
)

// HomeHandlers godoc
// @Summary Текущая версия API
// @Produce json
// @Success 200 {object} models.TVersion
// @Router /home/ [post]
func HomeHandlers(c *gin.Context) {
	var vers models.TVersion
	vers.BuildTime = version.BuildTime
	vers.Commit = version.Commit
	vers.Release = version.Release
	c.JSON(http.StatusOK, vers)

}
