basePath: /billing/api/v1
definitions:
  models.TAssignee:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  models.TClaimApplicant:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  models.TClaimRecipient:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  models.TClient:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      representative:
        $ref: '#/definitions/models.TRepresentatives'
      type:
        type: string
    type: object
  models.TData_req:
    properties:
      user:
        type: string
    type: object
  models.TData_resp:
    properties:
      status:
        type: integer
    type: object
  models.TDecisions:
    properties:
      message:
        type: string
    type: object
  models.TDelo:
    properties:
      assigneEmail:
        type: string
      assigneName:
        type: string
      assignee:
        $ref: '#/definitions/models.TAssignee'
      claimApplicant:
        $ref: '#/definitions/models.TClaimApplicant'
      claimRecipient:
        $ref: '#/definitions/models.TClaimRecipient'
      client:
        $ref: '#/definitions/models.TClient'
      ctime:
        description: дата создания дела <Дата>
        type: string
      dateOfReceivedClaim:
        description: дата отправки претензии <Дата>,
        type: string
      dateOfSendClaim:
        type: string
      decisions:
        $ref: '#/definitions/models.TDecisions'
      declarantEmail:
        description: email заявителя <Строковое значение> - устаревшее поле, сохранённое
          для совместимости, его надо игнорировать и использовать объект client,
        type: string
      declarantName:
        description: имя заявителя <Строковое значение> - устаревшее поле, сохранённое
          для совместимости, его надо игнорировать и использовать объект client,
        type: string
      dueDate:
        description: ближайший норматив <Дата и время>,
        type: string
      fields:
        type: string
      id:
        description: внешний id дела <Строковое значение>
        type: string
      issueDescription:
        description: описание дела  <Строковое значение>
        type: string
      issueSubject:
        description: название дела <Строковое значение>
        type: string
      links:
        $ref: '#/definitions/models.TLinks'
      serviceId:
        description: внешний id категории <Строковое значение>
        type: string
      serviceName:
        description: название категории <Строковое значение>
        type: string
    type: object
  models.TLinks:
    properties:
      link:
        type: string
      name:
        type: string
    type: object
  models.TRepresentatives:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  models.TVersion:
    properties:
      buildTime:
        type: string
      commit:
        type: string
      release:
        type: string
    type: object
host: localhost:5000
info:
  contact:
    email: servicedesk@tattelecom.ru
    name: API Support
    url: http://servicedesk.tattelecom.ttc
  description: wbfywefqybfeyuf
  title: Swagger IRBiS API.
  version: "1.0"
paths:
  /:
    get:
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: body
      summary: Текущая версия API
  /changeclientcard/:
    post:
      consumes:
      - application/json
      description: Передача данных по делам из Jeffit во внешнюю систему
      parameters:
      - description: name search by q
        in: body
        name: q
        schema:
          $ref: '#/definitions/models.TDelo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TData_resp'
      summary: Сохраняет данные по делам в биллинговой системе
  /home/:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TVersion'
      summary: Текущая версия API
  /test/:
    post:
      consumes:
      - application/json
      description: получить строку по идентификатору
      parameters:
      - description: name search by q
        in: body
        name: q
        schema:
          $ref: '#/definitions/models.TData_req'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TData_resp'
      summary: Retrieves user based on given ID
swagger: "2.0"
