package main

import (
	routes "wifilogin/cmd/wifilogin/routes"
	"wifilogin/version"

	//	_ "test/docs" // docs is generated by Swag CLI, you have to import it.

	gin "github.com/gin-gonic/gin"
	logs "github.com/sirupsen/logrus"
)

var router *gin.Engine

func SetupRouter() *gin.Engine {
	logs.SetFormatter(&logs.JSONFormatter{})

	logs.WithFields(logs.Fields{
		"commit":     version.Commit,
		"build time": version.BuildTime,
		"release":    version.Release,
	}).Info("Starting the service...")

	router := gin.Default()

	//router.LoadHTMLGlob("templates/*")

	routes.InitializeRoutes(router)

	return router
}

// @title Swagger IRBiS API.
// @version 1.0
// @description wbfywefqybfeyuf
// @termsOfService

// @contact.name API Support
// @contact.url http://servicedesk.tattelecom.ttc
// @contact.email servicedesk@tattelecom.ru

// @host 192.168.114.121:5000
// @BasePath /wifi/api/v1
func main() {

	router := SetupRouter()
	/*if os.Args[1] != nil {
		port := "5000"
	}else {
		port := */
	router.Run(":5001")
}
